In [21]:
from datasets import load_dataset
import pandas as pd
import numpy as np

In [22]:
ds = load_dataset("nazimali/quran-question-answer-context")

In [23]:
ds

DatasetDict({
    train: Dataset({
        features: ['q_id', 'question', 'answer', 'q_word', 'q_topic', 'fine_class', 'class', 'ontology_concept', 'ontology_concept2', 'source', 'q_src_id', 'quetion_type', 'chapter_name', 'chapter_no', 'verse', 'answer_en', 'class_en', 'fine_class_en', 'ontology_concept2_en', 'ontology_concept_en', 'q_topic_en', 'q_word_en', 'question_en', 'chapter_name_en', 'verse_list', 'context', 'context_data', 'context_missing_verses'],
        num_rows: 1224
    })
})

In [24]:
df = ds["train"].to_pandas()
df

,q_id,question,answer,q_word,q_topic,fine_class,class,ontology_concept,ontology_concept2,source,...,ontology_concept2_en,ontology_concept_en,q_topic_en,q_word_en,question_en,chapter_name_en,verse_list,context,context_data,context_missing_verses
0,1,ما هو الكتاب الوحيد الذي لا يوجد أي ريب أو شك ...,هو كتاب الله (القرآن الكريم) . والدليل : الم{1...,ما,الكتاب,كتاب مقدس,كيان,القرآن,القرآن الكريم,QA,...,The Noble Quran,The Quran,The book,Not,What is the only book that is free from any do...,The Cow,"[1, 2]","Quran Surah 2 Ayah 1:\nAlif, Lam, Mim. (Only A...","[{""index"": 0, ""q_src_id"": 1, ""surah"": 2, ""ayah...",
1,2,هل ثمار الجنة تشبه ثمار الدنيا ؟,نعم . والدليل :وَبَشِّرِ الَّذِين آمَنُواْ وَع...,هل,ثمر الجنة,نعم-لا,تقريري,ثمر الجنة,صفاتها,QA,...,Her Qualities,Fruits of Paradise,Fruit of Paradise,Are,Are the fruits of paradise similar to the frui...,The Cow,[25],"Quran Surah 2 Ayah 25:\nAnd, (O Beloved Prophe...","[{""index"": 1, ""q_src_id"": 2, ""surah"": 2, ""ayah...",
2,3,كم موت وكم حياة للبشر ؟,موتان وحياتان . والدليل :كَيْفَ تَكْفُرُونَ بِ...,كم,موت وحياة,عدد,رقم,الموت,الإنسان وخلقه,QA,...,Man And His Nature,Death,Death and life,How Much,How many deaths and how many lives do humans h...,The Cow,[28],Quran Surah 2 Ayah 28:\nHow Can You Deny Allah...,"[{""index"": 2, ""q_src_id"": 3, ""surah"": 2, ""ayah...",
3,4,ما عدد السموات ؟,سبع سماوات . والدليل :هُوَ الَّذِي خَلَقَ لَكُ...,ما,السموات,عدد,رقم,السموات,حقائق في الكون,QA,...,Facts In The Universe,The heavens,heavens,No,How many heavens are there?,The Cow,[29],Quran Surah 2 Ayah 29:\nHe Is The One Who Crea...,"[{""index"": 3, ""q_src_id"": 4, ""surah"": 2, ""ayah...",
4,5,ماذا تعلم آدم عليه السلام من الله جل جلاله وكا...,علم الأسماء . والدليل : وَعَلَّمَ آدَمَ الأَسْ...,ماذا,الأسماء,مصطلح,كيان,الأسماء,أعلم,QA,...,I Know,Names,Nouns,What,What did Adam (peace be upon him) learn from A...,The Cow,[31],Quran Surah 2 Ayah 31:\nAnd Allah Taught Adam ...,"[{""index"": 4, ""q_src_id"": 5, ""surah"": 2, ""ayah...",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1219,1221,إِنَّ إِبْرَاهِيمَ لَحَلِيمٌ أَوَّاهٌ مُّنِيبٌ...,إن إبراهيم عليه السلام كثير الحلم لا يحب المعا...,اشرح,آية,شرح,وصف,تفسير,آية,QA,...,Verse,Tafsir,Verse,Explain,"Indeed, Abraham was forbearing, often turning ...",Hûd,[75],"Quran Surah 11 Ayah 75:\nAssuredly, Ibrahim (A...","[{""index"": 1219, ""q_src_id"": 1221, ""surah"": 11...",
1220,1222,وَلَمَّا جَاءتْ رُسُلُنَا لُوطاً سِيءَ بِهِمْ ...,لأنهم حسان الوجوه في صورة أضياف عليه فخاف عليه...,لماذا,لما جاء,سبب,وصف,لوط,نبي,QA,...,Prophet,Lut,When he came,Why,Why did Lot (peace be upon him) grieve when th...,Hûd,[77],Quran Surah 11 Ayah 77:\nAnd When Our Deputed ...,"[{""index"": 1220, ""q_src_id"": 1222, ""surah"": 11...",
1221,1223,قَالَ لَوْ أَنَّ لِي بِكُمْ قُوَّةً أَوْ آوِي ...,"لو أن لي بكم قوة وأنصارًا, أو أركَن إلى عشيرة ...",ما,لَوْ أَنَّ لِي بِكُمْ قُوَّةً أَوْ آوِي إِلَى ...,معنى,وصف,معنى كلمة,كلمة,QA,...,Word,meaning of the word,"If only I had power over you, or could take re...",Not,What does Lut (peace be upon him) mean by his ...,Hûd,[80],Quran Surah 11 Ayah 80:\nLut (Lot) Said: ‘Woul...,"[{""index"": 1221, ""q_src_id"": 1223, ""surah"": 11...",
1222,1224,وَقَالَ لِفِتْيَانِهِ اجْعَلُواْ بِضَاعَتَهُمْ...,قال يوسف لغلمانه: اجعلوا ثمن ما أخذوه في أمتعت...,اشرح,آية,شرح,وصف,تفسير,آية,QA,...,Verse,Tafsir,Verse,Explain,"And he said to his young men, 'Put their merch...",Joseph,[62],Quran Surah 12 Ayah 62:\nAnd Yusuf (Joseph) Sa...,"[{""index"": 1222, ""q_src_id"": 1224, ""surah"": 12...",
1223,1225,وَلَمَّا فَتَحُواْ مَتَاعَهُمْ وَجَدُواْ بِضَا...,أي : نجلب طعامًا وفيرًا لأهلنا.,ما,وَنَمِيرُ أَهْلَنَا,معنى,وصف,معنى كلمة,كلمة,QA,...,Word,meaning of the word,And we will bring back our people,Not,,Joseph,[65],Quran Surah 12 Ayah 65:\nAnd When They Opened ...,"[{""index"": 1223, ""q_src_id"": 1225, ""surah"": 12...",

In [25]:
df.columns.tolist()

['q_id',
 'question',
 'answer',
 'q_word',
 'q_topic',
 'fine_class',
 'class',
 'ontology_concept',
 'ontology_concept2',
 'source',
 'q_src_id',
 'quetion_type',
 'chapter_name',
 'chapter_no',
 'verse',
 'answer_en',
 'class_en',
 'fine_class_en',
 'ontology_concept2_en',
 'ontology_concept_en',
 'q_topic_en',
 'q_word_en',
 'question_en',
 'chapter_name_en',
 'verse_list',
 'context',
 'context_data',
 'context_missing_verses']

In [26]:
"""
columns needed:

1- question_en
2- answer_en
3- chapter_no
4- verse_list
"""

'\ncolumns needed:\n\n1- question_en\n2- answer_en\n3- chapter_no\n4- verse_list\n'

In [8]:
qa_df = df[["question_en", "answer_en", "chapter_no", "verse_list"]].copy()

In [9]:
qa_df

,question_en,answer_en,chapter_no,verse_list
0,What is the only book that is free from any do...,This is the Book of Allah (the Quran). The evi...,2,"[1, 2]"
1,Are the fruits of paradise similar to the frui...,"Yes, and the evidence: 'And give good news to ...",2,[25]
2,How many deaths and how many lives do humans h...,"And you were dead, and He gave you life, then ...",2,[28]
3,How many heavens are there?,He it is Who created for you all that is in th...,2,[29]
4,What did Adam (peace be upon him) learn from A...,"He taught Adam the names of all things, then H...",2,[31]
...,...,...,...,...
1219,"Indeed, Abraham was forbearing, often turning ...","Abraham, peace be upon him, is patient, dislik...",11,[75]
1220,Why did Lot (peace be upon him) grieve when th...,He feared for them because they were handsome-...,11,[77]
1221,What does Lut (peace be upon him) mean by his ...,"If I had power and supporters among you, or if...",11,[80]
1222,"And he said to his young men, 'Put their merch...",Yusuf said to his servants: 'Make the price of...,12,[62]
1223,,We bring abundant food for our family.,12,[65]

In [10]:
qa_df.isnull().sum()

question_en    0
answer_en      0
chapter_no     0
verse_list     0
dtype: int64

In [11]:
text = qa_df.loc[30, "question_en"]
print(repr(text))

''

In [12]:
qa_df["question_en"] = (
    qa_df["question_en"]
    .replace(r"^\s*$", np.nan, regex=True)
)

In [13]:
qa_df.isnull().sum()

question_en    33
answer_en       0
chapter_no      0
verse_list      0
dtype: int64

In [14]:
qa_df = qa_df.dropna(subset=["question_en"])

In [15]:
qa_df

,question_en,answer_en,chapter_no,verse_list
0,What is the only book that is free from any do...,This is the Book of Allah (the Quran). The evi...,2,"[1, 2]"
1,Are the fruits of paradise similar to the frui...,"Yes, and the evidence: 'And give good news to ...",2,[25]
2,How many deaths and how many lives do humans h...,"And you were dead, and He gave you life, then ...",2,[28]
3,How many heavens are there?,He it is Who created for you all that is in th...,2,[29]
4,What did Adam (peace be upon him) learn from A...,"He taught Adam the names of all things, then H...",2,[31]
...,...,...,...,...
1218,Who is the wife of Ibrahim (peace be upon him)...,She is Sarah.,11,[71]
1219,"Indeed, Abraham was forbearing, often turning ...","Abraham, peace be upon him, is patient, dislik...",11,[75]
1220,Why did Lot (peace be upon him) grieve when th...,He feared for them because they were handsome-...,11,[77]
1221,What does Lut (peace be upon him) mean by his ...,"If I had power and supporters among you, or if...",11,[80]
1222,"And he said to his young men, 'Put their merch...",Yusuf said to his servants: 'Make the price of...,12,[62]

In [16]:
i = 25
print(qa_df['question_en'][i])
print("_____________________")
print(qa_df['answer_en'][i])
print("_____________________")
print(qa_df['chapter_no'][i], qa_df['verse_list'][i])

Recite some of the trials that Allah (Exalted is He) has put the believers through.
_____________________
Fear - Hunger - Lack of money - Death - Disease - Destruction of crops. And the evidence: 'And We will certainly put you to test with fear and hunger and loss of property and lives and crops. But give glad tidings to the steadfast.' (2:155) - The Cow.
_____________________
2 [155]

In [17]:
qa_df.loc[:, "answer_en"] = qa_df["answer_en"].str.replace(r"\(.*?\)", "", regex=True).str.strip()
qa_df.loc[:, "question_en"] = qa_df["question_en"].str.replace(r"\(.*?\)", "", regex=True).str.strip()

In [20]:
qa_df.to_csv("question_answering.csv", encoding="utf-8")