In [1]:
import pandas
import pandas as pd
import re
import unicodedata
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from tqdm import tqdm
import time

In [4]:
df = pd.read_csv("combined_tafseer.csv")
df

,Surah Number,Ayah Number,Text
0,1,1,Introduction to Fatihah\nWhich was revealed in...
1,1,2,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...
2,1,3,"Allah said next,\nالرَّحْمَـنِ الرَّحِيمِ\n(Ar..."
3,1,4,Indicating Sovereignty on the Day of Judgment\...
4,1,5,The Linguistic and Religious Meaning of `Ibada...
...,...,...,...
6231,114,2,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
6232,114,3,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
6233,114,4,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
6234,114,5,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...
6235,114,6,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...

In [9]:
df.iloc[0]["Text"]

'Introduction to Fatihah\nWhich was revealed in Makkah\nThe Meaning of Al-Fatihah and its Various Names\nThis Surah is called\n- Al-Fatihah, that is, the Opener of the Book, the Surah with which prayers are begun.\n- It is also called, Umm Al-Kitab (the Mother of the Book), according to the majority of the scholars.\nIn an authentic Hadith recorded by At-Tirmidhi, who graded it Sahih, Abu Hurayrah said that the Messenger of Allah ﷺ said,\nالْحَمْدُ للهِ رَبَ الْعَالَمِينَ أُمُّ الْقُرْآنِ وَأُمُّ الْكِتَابِ وَالسَّبْعُ الْمَثَانِي وَالْقُرْآنُ الْعَظِيمُ\nAl-Hamdu lillahi Rabbil-`Alamin is the Mother of the Qur\'an, the Mother of the Book, and the seven repeated Ayat of the Glorious Qur\'an.It is also called Al-Hamd and As-Salah, because the Prophet ﷺ said that his Lord said,\nقَسَمْتُ الصَّلَاةَ بَيْنِي وَبَيْنَ عَبْدِي نِصْفَيْنِ، فَإِذَا قَالَ الْعَبْدُ:الْحَمْدُ للهِ رَبِّ الْعَالَمِينَ، قَالَ اللهُ: حَمِدَنِي عَبْدِي\nThe prayer (i.e., Al-Fatihah) is divided into two halves between Me and My servants. When the servant says, `All praise is due to Allah, the Lord of existence,\' Allah says, \'My servant has praised Me. Al-Fatihah was called the Salah, because reciting it is a condition for the correctness of Salah - the prayer. Al-Fatihah was also called Ash-Shifa\' (the Cure).It is also called Ar-Ruqyah (remedy), since in the Sahih, there is the narration of Abu Sa`id telling the story of the Companion who used Al-Fatihah as a remedy for the tribal chief who was poisoned. Later, the Messenger of Allah ﷺ said to a Companion,\nوَمَا يُدْرِيكَ أَنَّهَا رُقْيَةٌ\nHow did you know that it is a Ruqyah?Al-Fatihah was revealed in Makkah as Ibn Abbas, Qatadah and Abu Al-Aliyah stated.Allah said,\nوَلَقَدْ ءاتَيْنَـكَ سَبْعًا مِّنَ الْمَثَانِي\nAnd indeed, We have bestowed upon you the seven Mathani (seven repeatedly recited verses), (i.e. Surah Al-Fatihah) (15:87). Allah knows best.\nHow many Ayat does Al-Fatihah contain\nThere is no disagreement over the view that Al-Fatihah contains seven Ayat. According to the majority of the reciters of Al-Kufah, a group of the Companions, the Tabi`in, and a number of scholars from the successive generations, the Bismillah is a separate Ayah in its beginning. We will mention this subject again soon, if Allah wills, and in Him we trust.\nThe Number of Words and Letters in Al-Fatihah\nThe scholars say that Al-Fatihah consists of twenty-five words, and that it contains one hundred and thirteen letters.\nThe Reason it is called Umm Al-Kitab\nIn the beginning of the Book of Tafsir, in his Sahih, Al-Bukhari said; "It is called Umm Al-Kitab, because the Qur\'an starts with it and because the prayer is started by reciting it." It was also said that it is called Umm Al-Kitab, because it contains the meanings of the entire Qur\'an. Ibn Jarir said, "The Arabs call every comprehensive matter that contains several specific areas an Umm. For instance, they call the skin that surrounds the brain, Umm Ar-Ra\'s. They also call the flag that gathers the ranks of the army an Umm." He also said, "Makkah was called Umm Al-Qura, (the Mother of the Villages) because it is the grandest and the leader of all villages. It was also said that the earth was made starting from Makkah."\nFurther, Imam Ahmad recorded that Abu Hurayrah narrated about Umm Al-Qur\'an that the Prophet ﷺ said,\n«هِيَ أُمُّ الْقُرْآنِ وَهِيَ السَّبْعُ الْمَثَانِي وَهِيَ الْقُرْآنُ الْعَظِيمُ»\n(It is Umm Al-Qur\'an, the seven repeated (verses) and the Glorious Qur\'an.)\nAlso, Abu Ja`far, Muhammad bin Jarir At-Tabari recorded Abu Hurayrah saying that the Messenger of Allah ﷺ about Al-Fatihah,\n«هِيَ أُمُّ الْقُرْآنِ وَهِيَ فَاتِحَةُ الْكِتَابِ وَهِيَ السَّبْعُ الْمَثَانِي»\n(It is Umm Al-Qur\'an, Al-Fatihah of the Book (the Opener of the Qur\'an) and the seven repeated (verses).)\nVirtues of Al-Fatihah\nImam Ahmad bin Hanbal recorded in the Musnad that Abu Sa`id bin Al-Mu`alla said, "I was praying when the Prophet ﷺ called me, so I did not answer him until I finished the prayer. I then went to him and he said, (What prevented you from coming) I said, \'O Messenger of Allah ﷺ! I was praying.\' He said, (`Didn\'t Allah say),\nيأَيُّهَا الَّذِينَ ءَامَنُواْ اسْتَجِيبُواْ لِلَّهِ وَلِلرَّسُولِ إِذَا دَعَاكُمْ لِمَا يُحْيِيكُمْ\n(O you who believe! Answer Allah (by obeying Him) and (His) Messenger when he () calls you to that which gives you life) He then said,\n«لَأُعَلِّمَنَّكَ أَعْظَمَ سُورَةٍ فِي الْقُرْآنِ قَبْلَ أَنْ تَخْرُجَ مِنَ الْمَسْجِدِ»\n(I will teach you the greatest Surah in the Qur\'an before you leave the Masjid.) He held my hand and when he was about to leave the Masjid, I said, `O Messenger of Allah ﷺ! You said: I will teach you the greatest Surah in the Qur\'an.\' He said, (Yes.)\nالْحَمْدُ للَّهِ رَبِّ الْعَـلَمِينَ\n(Al-Hamdu lillahi Rabbil-`Alamin)"\n«نَعَمْ هِيَ السَّبْعُ الْمَثَانِي وَالْقُرْآنُ الْعَظِيمُ الَّذِي أُوتِيتُهُ»\n(It is the seven repeated (verses) and the Glorious Qur\'an that I was given.)"\nAl-Bukhari, Abu Dawud, An-Nasa\'i and Ibn Majah also recorded this Hadith.\nAlso, Imam Ahmad recorded that Abu Hurayrah said, "The Messenger of Allah ﷺ out while Ubayy bin Ka`b was praying and said, (O Ubayy!) Ubayy did not answer him. The Prophet ﷺ said, (O Ubayy!) Ubayy prayed faster then went to the Messenger of Allah ﷺ saying, `Peace be unto you, O Messenger of Allah ﷺ !\' He said, (Peace be unto you. O Ubayy, what prevented you from answering me when I called you) He said, `O Messenger of Allah ﷺ! I was praying.\' He said, (Did you not read among what Allah has sent down to me,)\nاسْتَجِيبُواْ لِلَّهِ وَلِلرَّسُولِ إِذَا دَعَاكُمْ لِمَا يُحْيِيكُمْ\n(Answer Allah (by obeying Him) and (His) Messenger when he () calls you to that which gives you life) He said, `Yes, O Messenger of Allah ﷺ ! I will not do it again.\' the Prophet ﷺ said,\n«أَتُحِبُّ أَنْ أُعَلِّمَكَ سُورَةً لَمْ تَنْزِلْ لَا فِي التَّورَاةِ وَلَا فِي الْإِنْجِيلِ وَلَا فِي الزَّبُورِ وَلَا فِي الْفُرْقَانِ مِثْلَهَا؟»\n(Would you like me to teach you a Surah the likes of which nothing has been revealed in the Tawrah, the Injil, the Zabur (Psalms) or the Furqan (the Qur\'an)) He said, `Yes, O Messenger of Allah ﷺ !\' The Messenger of Allah ﷺ said, (I hope that I will not leave through this door until you have learned it.) He (Ka`b) said, `The Messenger of Allah ﷺ held my hand while speaking to me. Meanwhile I was slowing down fearing that he might reach the door before he finished his conversation. When we came close to the door, I said: O Messenger of Allah ﷺ ! What is the Surah that you have promised to teach me\' He said, (What do you read in the prayer.) Ubayy said, `So I recited Umm Al-Qur\'an to him.\' He said,\n«وَالَّذِي نَفْسِي بِيَدِهِ مَا أَنْزَلَ اللهُ فِي التَّورَاةِ وَلَا فِي الْإِنْجِيلِ وَلَا فِي الزَّبُورِ وَلَا فِي الْفُرْقَانِ مِثْلَهَا إِنَّهَا السَّبْعُ الْمَثَانِي»\n(By Him in Whose Hand is my soul! Allah has never revealed in the Tawrah, the Injil, the Zabur or the Furqan a Surah like it. It is the seven repeated verses that I was given.)"\nAlso, At-Tirmidhi recorded this Hadith and in his narration, the Prophet ﷺ said,\n«إِنَّهَا مِنَ السَّبْعِ الْمَثَانِي وَالْقُرْآنِ الْعَظِيمِ الَّذِي أُعْطِيتُهُ»\n(It is the seven repeated verses and the Glorious Qur\'an that I was given.) At-Tirmidhi then commented that this Hadith is Hasan Sahih.\nThere is a similar Hadith on this subject narrated from Anas bin Malik Further, `Abdullah, the son of Imam Ahmad, recorded this Hadith from Abu Hurayrah from Ubayy bin Ka`b, and he mentioned a longer but similar wording for the above Hadith. In addition, At-Tirmidhi and An-Nasa\'i recorded this Hadith from Abu Hurayrah from Ubayy bin Ka`b who said that the Messenger of Allah ﷺ said,\n«مَا أَنْزَل اللهُ فِي التَّورَاةِ وَلَا فِي الْإِنْجِيلِ مِثْلَ أُمِّ الْقُرْآنِ وَهِيَ السَّبْعُ الْمَثَانِي وَهِيَ مَقْسُومَةٌ بَيْنِي وَبَيْنَ عَبْدِي نِصْفَيْنِ»\n(Allah has never revealed in the Tawrah or the Injil anything similar to Umm Al-Qur\'an.\nIt is the seven repeated verses and it is divided into two halves between Allah and His servant.)\nThis is the wording reported by An-Nasa\'i. At-Tirmidhi said that this Hadith is Hasan Gharib.\nAlso, Imam Ahmad recorded that Ibn Jabir said, "I went to the Messenger of Allah ﷺ after he had poured water (for purification) and said, `Peace be unto you, O Messenger of Allah ﷺ !\' He did not answer me. So I said again, `Peace be unto you, O Messenger of Allah ﷺ !\' Again, he did not answer me, so I said again, `Peace be unto you, O Messenger of Allah ﷺ !\' Still he did not answer me. The Messenger of Allah ﷺ went while I was following him, until he arrived at his residence. I went to the Masjid and sat there sad and depressed. The Messenger of Allah ﷺ came out after he performed his purification and said, (Peace and Allah\'s mercy be unto you, peace and Allah\'s mercy be unto you, peace and Allah\'s mercy be unto you.) He then said, (O `Abdullah bin Jabir! Should I inform you of the best Surah in the Qur\'an) I said, `Yes, O Messenger of Allah ﷺ !\' He said, (Read, `All praise be to Allah, the Lord of the existence,\' until you finish it.)" This Hadith has a good chain of narrators.\nSome scholars relied on this Hadith as evidence that some Ayat and Surahs have more virtues than others.\nFurthermore, in the chapter about the virtues of the Qur\'an, Al-Bukhari recorded that Abu Sa`id Al-Khudri said, "Once, we were on a journey when a female servant came and said, `The leader of this area has been poisoned and our people are away. Is there a healer among you\' Then a man whose healing expertise did not interest us stood for her, he read a Ruqyah for him, and he was healed. The chief gave him thirty sheep as a gift and some milk. When he came back to us we said to him, `You know of a (new) Ruqyah, or did you do this before\' He said, `I only used Umm Al-Kitab as Ruqyah.\' We said, `Do not do anything further until we ask the Messenger of Allah ﷺ.\' When we went back to Al-Madinah we mentioned what had happened to the Prophet ﷺ. The Prophet ﷺ said,\n«وَمَا كَانَ يُدْرِيهِ أَنَّهَا رُقْيَةٌ اقْسِمُوا وَاضْرِبُوا لِي بِسَهْمٍ»\n(Who told him that it is a Ruqyah Divide (the sheep) and reserve a share for me.)"\nAlso, Muslim recorded in his Sahih, and An-Nasa\'i in his Sunan that Ibn `Abbas said, "While Jibril (Gabriel) was with the Messenger of Allah ﷺ, he heard a noise from above. Jibril lifted his sight to the sky and said, `This is a door in heaven being open, and it has never been opened before now.\' An angel descended from that door and came to the Prophet ﷺ and said, `Receive the glad tidings of two lights that you have been given, which no other Prophet before you was given: the Opening of the Book and the last (three) Ayat of Surat Al-Baqarah. You will not read a letter of them, but will gain its benefit."\' This is the wording collected by An-Nasa\'i (Al-Kubra 5:12) and Muslim recorded similar wording (1:554).\nAl-Fatihah and the Prayer\nMuslim recorded that Abu Hurayrah said that the Prophet ﷺ said,\n«مَنْ صَلَى صَلَاةً لَمْ يَقْرَأْ فِيهَا أُمَّ الْقُرْآنِ فَهِيَ خِدَاجٌ ثَلَاثًا غَيْرُ تَمَامٍ»\n(Whoever performs any prayer in which he did not read Umm Al-Qur\'an, then his prayer is incomplete.) He said it thrice.\nAbu Hurayrah was asked, "When we stand behind the Imam" He said, "Read it to yourself, for I heard the Messenger of Allah ﷺ say,\n« قَالَ اللَّهُ عَزَّ وَجَلَّ: قَسَمْتُ الصّلَاةَ بَيْنِي وَبَيْنَ عَبْدِي نِصْفَيْنِ وَلِعَبْدِي مَا سَأَلَ فَإِذَا قَالَ:\nالْحَمْدُ للَّهِ رَبِّ الْعَـلَمِينَ ، قَالَ اللهُ: حَمِدَنِي عَبْدِي وَإِذَا قَالَ:\nالرَّحْمَـنِ الرَّحِيمِ ، قَالَ اللهُ: أَثْنى عَلَيَّ عَبْدِي، فَإذَا قَالَ:\nمَـلِكِ يَوْمِ الدِّينِ ، قَالَ اللهُ: مَجَّدَنِي عَبْدِي وَقَالَ مَرَّةً: فَوَّضَ إِلَيَّ عَبْدِي فَإِذَا قَالَ:\nإِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ ، قَالَ: هذَا بَيْنِي وَبَيْنَ عَبْدِي وَلِعَبْدِي مَا سَأَلَ، فَإِذَا قَالَ:\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ - صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ ، قَالَ اللهُ: هذَا لِعَبْدِي وَلِعَبْدِي مَا سَأَلَ»\n(Allah, the Exalted, said, `I have divided the prayer (Al-Fatihah) into two halves between Myself and My servant, and My servant shall have what he asks for.\' If he says,\nبِسْمِ اللَّهِ الرَّحْمَـنِ الرَّحِيمِ\n(1 In the Name of Allah, the Most Gracious, the Most Merciful.)\nالْحَمْدُ للَّهِ رَبِّ الْعَـلَمِينَ\n(2 All praise and thanks be to Allah, the Lord of existence.)\nAllah says, `My servant has praised Me.\' When the servant says,\nالرَّحْمَـنِ الرَّحِيمِ\n(3 The Most Gracious, the Most Merciful.)\nAllah says, `My servant has glorified Me.\' When he says,\nمَـلِكِ يَوْمِ الدِّينِ\n(4 The Owner of the Day of Recompense.) Allah says, `My servant has glorified Me,\' or `My servant has related all matters to Me.\' When he says,\nإِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ\n(5 You (alone) we worship, and You (alone) we ask for help.) Allah says, `This is between Me and My servant, and My servant shall acquire what he sought.\' When he says,\nاهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ - صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلاَ الضَّآلِّينَ\n(6 Guide us to the straight path.) (7 The way of those on whom You have granted Your grace, not (the way) of those who earned Your anger, nor of those who went astray), Allah says, `This is for My servant, and My servant shall acquire what he asked for.\')."\nThese are the words of An-Nasa\'i, while both Muslim and An-Nasa\'i collected the following wording, "A half of it is for Me and a half for My servant, and My servant shall acquire what he asked for."\nExplaining this Hadith\nThe last Hadith used the word Salah `prayer\' in reference to reciting the Qur\'an, (Al-Fatihah in this case) just as Allah said in another Ayah,\nوَلاَ تَجْهَرْ بِصَلاتِكَ وَلاَ تُخَافِتْ بِهَا وَابْتَغِ بَيْنَ ذَلِكَ سَبِيلاً\n(And offer your Salah (prayer) neither aloud nor in a low voice, but follow a way between.) meaning, with your recitation of the Qur\'an, as the Sahih related from Ibn `Abbas. Also, in the last Hadith, Allah said, "I have divided the prayer between Myself and My servant into two halves, a half for Me and a half for My servant. My servant shall have what he asked for." Allah next explained the division that involves reciting Al-Fatihah, demonstrating the importance of reciting the Qur\'an during the prayer, which is one of the prayer\'s greatest pillars. Hence, the word `prayer\' was used here although only a part of it was actually being referred to, that is, reciting the Qur\'an. Similarly, the word `recite\' was used where prayer is meant, as demonstrated by Allah\'s statement,\nوَقُرْءَانَ الْفَجْرِ إِنَّ قُرْءَانَ الْفَجْرِ كَانَ مَشْهُودًا\n(And recite the Qur\'an in the early dawn.Verily, the recitation of the Qur\'an in the early dawn is ever witnessed.) in reference to the Fajr prayer. The Two Sahihs recorded that the angels of the night and the day attend this prayer.\nReciting Al-Fatihah is required in Every Rak`ah of the Prayer\nAll of these facts testify to the requirement that reciting the Qur\'an (Al-Fatihah) in the prayer is required, and there is a consensus between the scholars on this ruling. The Hadith that we mentioned also testifies to this fact, for the Prophet ﷺ said,\n«مَنْ صَلَّى صَلَاةً لَمْ يَقْرَأْ فِيهَا بِأُمِّ الْقُرْآنِ فَهِيَ خِدَاجٌ»\n(Whoever performs any prayer in which he did not recite Umm Al-Qur\'an, his prayer is incomplete.)\nAlso, the Two Sahihs recorded that `Ubadah bin As-Samit said that the Messenger of Allah ﷺ said,\n«لَا صَلَاةَ لِمَنْ لَمْ يَقْرَأْ بِفَاتِحَةِ الْكِتَابِ»\n(There is no prayer for whoever does not recite the Opening of the Book.)\nAlso, the Sahihs of Ibn Khuzaymah and Ibn Hibban recorded that Abu Hurayrah said that the Messenger of Allah ﷺ said,\n«لَا تُجْزِئُ صَلَاةٌ لَا يُقْرَأُ فِيهَا بِأُمِّ الْقُرآنِ»\n(The prayer during which Umm Al-Qur\'an is not recited is invalid.)\nThere are many other Hadiths on this subject. Therefore, reciting the Opening of the Book, during the prayer by the Imam and those praying behind him, is required in every prayer, and in every Rak`ah.\nThe Tafsir of Isti`adhah (seeking Refuge)\nAllah said,\nخُذِ الْعَفْوَ وَأْمُرْ بِالْعُرْفِ وَأَعْرِض عَنِ الْجَـهِلِينَ - وَإِمَّا يَنَزَغَنَّكَ مِنَ الشَّيْطَـنِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ إِنَّهُ سَمِيعٌ عَلِيمٌ\n(Show forgiveness, enjoin what is good, and stay away from the foolish (i.e. don\'t punish them). And if an evil whisper comes to you from Shaytan (Satan), then seek refuge with Allah. Verily, He is Hearing, Knowing) (7:199-200),\nادْفَعْ بِالَّتِى هِىَ أَحْسَنُ السَّيِّئَةَ نَحْنُ أَعْلَمُ بِمَا يَصِفُونَ - وَقُلْ رَّبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيـطِينِ - وَأَعُوذُ بِكَ رَبِّ أَن يَحْضُرُونِ\n(Repel evil with that which is better. We are Best-Acquainted with things they utter. And say: "My Lord! I seek refuge with You from the whisperings (suggestions) of the Shayatin (devils). And I seek refuge with You, My Lord! lest they should come near me.") (23:96-98) and,\nوَلاَ تَسْتَوِى الْحَسَنَةُ وَلاَ السَّيِّئَةُ ادْفَعْ بِالَّتِى هِىَ أَحْسَنُ فَإِذَا الَّذِى بَيْنَكَ وَبَيْنَهُ عَدَاوَةٌ كَأَنَّهُ وَلِىٌّ حَمِيمٌ - وَمَا يُلَقَّاهَا إِلاَّ الَّذِينَ صَبَرُواْ وَمَا يُلَقَّاهَآ إِلاَّ ذُو حَظِّ عَظِيمٍ - وَإِمَّا يَنزَغَنَّكَ مِنَ الشَّيْطَـنِ نَزْغٌ فَاسْتَعِذْ بِاللَّهِ إِنَّهُ هُوَ السَّمِيعُ الْعَلِيمُ\n(Repel (an evil) with one which is better, then verily he with whom there was enmity between you, (will become) as though he was a close friend. But none is granted it except those who are patient ـ and none is granted it except the owner of the great portion (of happiness in the Hereafter, i.e. Paradise and of a high moral character) in this world. And if an evil whisper from Shaytan tries to turn you away (O Muhammad ﷺ) (from doing good), then seek refuge in Allah. Verily, He is the Hearing, the Knowing.) (41:34-36) These are the only three Ayat that carry this meaning. Allah commanded that we be lenient human enemy, so that his soft nature might make him an ally and a supporter. He also commanded that we seek refuge from the satanic enemy, because the devil does not relent in his enmity if we treat him with kindness and leniency. The devil only seeks the destruction of the Son of Adam due to the vicious enmity and hatred he has always had towards man\'s father, Adam. Allah said,\nيَـبَنِى آدَمَ لاَ يَفْتِنَنَّكُمُ الشَّيْطَـنُ كَمَآ أَخْرَجَ أَبَوَيْكُم مِّنَ الْجَنَّةِ\n(O Children of Adam! Let not Shaytan deceive you, as he got your parents Adam and Hawwa\' (Eve) out of Paradise) (7:27),\nإِنَّ الشَّيْطَـنَ لَكُمْ عَدُوٌّ فَاتَّخِذُوهُ عَدُوّاً إِنَّمَا يَدْعُو حِزْبَهُ لِيَكُونُواْ مِنْ أَصْحَـبِ السَّعِيرِ\n(Surely, Shaytan is an enemy to you, so take (treat) him as an enemy. He only invites his Hizb (followers) that they may become the dwellers of the blazing Fire) (35:6) and,\nأَفَتَتَّخِذُونَهُ وَذُرِّيَّتَهُ أَوْلِيَآءَ مِن دُونِى وَهُمْ لَكُمْ عَدُوٌّ بِئْسَ لِلظَّـلِمِينَ بَدَلاً\n(Will you then take him (Iblis) and his offspring as protectors and helpers rather than Me while they are enemies to you What an evil is the exchange for the Zalimun (polytheists, and wrongdoers, etc)) (18:50).\nThe devil assured Adam that he wanted to advise him, but he was lying. Hence, how would he treat us after he had vowed,\nفَبِعِزَّتِكَ لأغْوِيَنَّهُمْ أَجْمَعِينَ إِلاَّ عِبَادَكَ مِنْهُمُ الْمُخْلَصِينَ\n("By Your might, then I will surely, mislead them all. Except Your chosen servants among them (i.e. faithful, obedient, true believers of Islamic Monotheism).") (38:82-83)\nAlso, Allah said,\nفَإِذَا قَرَأْتَ الْقُرْءَانَ فَاسْتَعِذْ بِاللَّهِ مِنَ الشَّيْطَـنِ الرَّجِيمِ\nإِنَّهُ لَيْسَ لَهُ سُلْطَانٌ عَلَى الَّذِينَ ءَامَنُواْ وَعَلَى رَبِّهِمْ يَتَوَكَّلُونَ - إِنَّمَا سُلْطَـنُهُ عَلَى الَّذِينَ يَتَوَلَّوْنَهُ وَالَّذِينَ هُم بِهِ مُشْرِكُونَ\n(So when you want to recite the Qur\'an, seek refuge with All

In [5]:
ARABIC_TASHKEEL = re.compile(r'[\u0617-\u061A\u064B-\u0652\u0657-\u065F\u0670]')



def preprocess_tafsir_text(text: str) -> str:
    if not isinstance(text, str):
        return ""

    soup = BeautifulSoup(text, "html.parser")
    text = soup.get_text(separator=" \n ")

    text = unicodedata.normalize("NFKC", text)

    text = re.sub(ARABIC_TASHKEEL, '', text)

    text = text.replace('«', '(').replace('»', ')').replace('ـ', '')

    text = re.sub('[إأآٱ]', 'ا', text)
    text = re.sub('ى', 'ي', text)
    text = re.sub('ؤ', 'و', text)
    text = re.sub('ئ', 'ي', text)
    text = re.sub('ة', 'ه', text)
    text = re.sub('ﷺ', '', text)

    text = re.sub(
        r'\((\d+):(\d+)(?:-(\d+))?\)',
        r'(سوره \1 الايه \2\3)',
        text
    )
    lines = []
    for line in text.splitlines():
        line = re.sub(r'\s+', ' ', line).strip()
        if line:
            lines.append(line)

    text = "\n".join(lines)
    text = re.sub(r'\n{2,}', '\n', text).strip()

    return text

In [6]:
preprocess_tafsir_text(df['Text'][0])

'Introduction to Fatihah\nWhich was revealed in Makkah\nThe Meaning of Al-Fatihah and its Various Names\nThis Surah is called\n- Al-Fatihah, that is, the Opener of the Book, the Surah with which prayers are begun.\n- It is also called, Umm Al-Kitab (the Mother of the Book), according to the majority of the scholars.\nIn an authentic Hadith recorded by At-Tirmidhi, who graded it Sahih, Abu Hurayrah said that the Messenger of Allah صلي الله عليه وسلم said,\nالحمد لله رب العالمين ام القران وام الكتاب والسبع المثاني والقران العظيم\nAl-Hamdu lillahi Rabbil-`Alamin is the Mother of the Qur\'an, the Mother of the Book, and the seven repeated Ayat of the Glorious Qur\'an.It is also called Al-Hamd and As-Salah, because the Prophet صلي الله عليه وسلم said that his Lord said,\nقسمت الصلاه بيني وبين عبدي نصفين، فاذا قال العبد:الحمد لله رب العالمين، قال الله: حمدني عبدي\nThe prayer (i.e., Al-Fatihah) is divided into two halves between Me and My servants. When the servant says, `All praise is due to Allah, the Lord of existence,\' Allah says, \'My servant has praised Me. Al-Fatihah was called the Salah, because reciting it is a condition for the correctness of Salah - the prayer. Al-Fatihah was also called Ash-Shifa\' (the Cure).It is also called Ar-Ruqyah (remedy), since in the Sahih, there is the narration of Abu Sa`id telling the story of the Companion who used Al-Fatihah as a remedy for the tribal chief who was poisoned. Later, the Messenger of Allah صلي الله عليه وسلم said to a Companion,\nوما يدريك انها رقيه\nHow did you know that it is a Ruqyah?Al-Fatihah was revealed in Makkah as Ibn Abbas, Qatadah and Abu Al-Aliyah stated.Allah said,\nولقد ءاتينك سبعا من المثاني\nAnd indeed, We have bestowed upon you the seven Mathani (seven repeatedly recited verses), (i.e. Surah Al-Fatihah) (سوره 15 الايه 87). Allah knows best.\nHow many Ayat does Al-Fatihah contain\nThere is no disagreement over the view that Al-Fatihah contains seven Ayat. According to the majority of the reciters of Al-Kufah, a group of the Companions, the Tabi`in, and a number of scholars from the successive generations, the Bismillah is a separate Ayah in its beginning. We will mention this subject again soon, if Allah wills, and in Him we trust.\nThe Number of Words and Letters in Al-Fatihah\nThe scholars say that Al-Fatihah consists of twenty-five words, and that it contains one hundred and thirteen letters.\nThe Reason it is called Umm Al-Kitab\nIn the beginning of the Book of Tafsir, in his Sahih, Al-Bukhari said; "It is called Umm Al-Kitab, because the Qur\'an starts with it and because the prayer is started by reciting it." It was also said that it is called Umm Al-Kitab, because it contains the meanings of the entire Qur\'an. Ibn Jarir said, "The Arabs call every comprehensive matter that contains several specific areas an Umm. For instance, they call the skin that surrounds the brain, Umm Ar-Ra\'s. They also call the flag that gathers the ranks of the army an Umm." He also said, "Makkah was called Umm Al-Qura, (the Mother of the Villages) because it is the grandest and the leader of all villages. It was also said that the earth was made starting from Makkah."\nFurther, Imam Ahmad recorded that Abu Hurayrah narrated about Umm Al-Qur\'an that the Prophet صلي الله عليه وسلم said,\n(هي ام القران وهي السبع المثاني وهي القران العظيم)\n(It is Umm Al-Qur\'an, the seven repeated (verses) and the Glorious Qur\'an.)\nAlso, Abu Ja`far, Muhammad bin Jarir At-Tabari recorded Abu Hurayrah saying that the Messenger of Allah صلي الله عليه وسلم about Al-Fatihah,\n(هي ام القران وهي فاتحه الكتاب وهي السبع المثاني)\n(It is Umm Al-Qur\'an, Al-Fatihah of the Book (the Opener of the Qur\'an) and the seven repeated (verses).)\nVirtues of Al-Fatihah\nImam Ahmad bin Hanbal recorded in the Musnad that Abu Sa`id bin Al-Mu`alla said, "I was praying when the Prophet صلي الله عليه وسلم called me, so I did not answer him until I finished the prayer. I then went to him and he said, (What prevented you from coming) I said, \'O Messenger of Allah صلي الله عليه وسلم! I was praying.\' He said, (`Didn\'t Allah say),\nيايها الذين ءامنوا استجيبوا لله وللرسول اذا دعاكم لما يحييكم\n(O you who believe! Answer Allah (by obeying Him) and (His) Messenger when he () calls you to that which gives you life) He then said,\n(لاعلمنك اعظم سوره في القران قبل ان تخرج من المسجد)\n(I will teach you the greatest Surah in the Qur\'an before you leave the Masjid.) He held my hand and when he was about to leave the Masjid, I said, `O Messenger of Allah صلي الله عليه وسلم! You said: I will teach you the greatest Surah in the Qur\'an.\' He said, (Yes.)\nالحمد لله رب العلمين\n(Al-Hamdu lillahi Rabbil-`Alamin)"\n(نعم هي السبع المثاني والقران العظيم الذي اوتيته)\n(It is the seven repeated (verses) and the Glorious Qur\'an that I was given.)"\nAl-Bukhari, Abu Dawud, An-Nasa\'i and Ibn Majah also recorded this Hadith.\nAlso, Imam Ahmad recorded that Abu Hurayrah said, "The Messenger of Allah صلي الله عليه وسلم out while Ubayy bin Ka`b was praying and said, (O Ubayy!) Ubayy did not answer him. The Prophet صلي الله عليه وسلم said, (O Ubayy!) Ubayy prayed faster then went to the Messenger of Allah صلي الله عليه وسلم saying, `Peace be unto you, O Messenger of Allah صلي الله عليه وسلم !\' He said, (Peace be unto you. O Ubayy, what prevented you from answering me when I called you) He said, `O Messenger of Allah صلي الله عليه وسلم! I was praying.\' He said, (Did you not read among what Allah has sent down to me,)\nاستجيبوا لله وللرسول اذا دعاكم لما يحييكم\n(Answer Allah (by obeying Him) and (His) Messenger when he () calls you to that which gives you life) He said, `Yes, O Messenger of Allah صلي الله عليه وسلم ! I will not do it again.\' the Prophet صلي الله عليه وسلم said,\n(اتحب ان اعلمك سوره لم تنزل لا في التوراه ولا في الانجيل ولا في الزبور ولا في الفرقان مثلها؟)\n(Would you like me to teach you a Surah the likes of which nothing has been revealed in the Tawrah, the Injil, the Zabur (Psalms) or the Furqan (the Qur\'an)) He said, `Yes, O Messenger of Allah صلي الله عليه وسلم !\' The Messenger of Allah صلي الله عليه وسلم said, (I hope that I will not leave through this door until you have learned it.) He (Ka`b) said, `The Messenger of Allah صلي الله عليه وسلم held my hand while speaking to me. Meanwhile I was slowing down fearing that he might reach the door before he finished his conversation. When we came close to the door, I said: O Messenger of Allah صلي الله عليه وسلم ! What is the Surah that you have promised to teach me\' He said, (What do you read in the prayer.) Ubayy said, `So I recited Umm Al-Qur\'an to him.\' He said,\n(والذي نفسي بيده ما انزل الله في التوراه ولا في الانجيل ولا في الزبور ولا في الفرقان مثلها انها السبع المثاني)\n(By Him in Whose Hand is my soul! Allah has never revealed in the Tawrah, the Injil, the Zabur or the Furqan a Surah like it. It is the seven repeated verses that I was given.)"\nAlso, At-Tirmidhi recorded this Hadith and in his narration, the Prophet صلي الله عليه وسلم said,\n(انها من السبع المثاني والقران العظيم الذي اعطيته)\n(It is the seven repeated verses and the Glorious Qur\'an that I was given.) At-Tirmidhi then commented that this Hadith is Hasan Sahih.\nThere is a similar Hadith on this subject narrated from Anas bin Malik Further, `Abdullah, the son of Imam Ahmad, recorded this Hadith from Abu Hurayrah from Ubayy bin Ka`b, and he mentioned a longer but similar wording for the above Hadith. In addition, At-Tirmidhi and An-Nasa\'i recorded this Hadith from Abu Hurayrah from Ubayy bin Ka`b who said that the Messenger of Allah صلي الله عليه وسلم said,\n(ما انزل الله في التوراه ولا في الانجيل مثل ام القران وهي السبع المثاني وهي مقسومه بيني وبين عبدي نصفين)\n(Allah has never revealed in the Tawrah or the Injil anything similar to Umm Al-Qur\'an.\nIt is the seven repeated verses and it is divided into two halves between Allah and His servant.)\nThis is the wording reported by An-Nasa\'i. At-Tirmidhi said that this Hadith is Hasan Gharib.\nAlso, Imam Ahmad recorded that Ibn Jabir said, "I went to the Messenger of Allah صلي الله عليه وسلم after he had poured water (for purification) and said, `Peace be unto you, O Messenger of Allah صلي الله عليه وسلم !\' He did not answer me. So I said again, `Peace be unto you, O Messenger of Allah صلي الله عليه وسلم !\' Again, he did not answer me, so I said again, `Peace be unto you, O Messenger of Allah صلي الله عليه وسلم !\' Still he did not answer me. The Messenger of Allah صلي الله عليه وسلم went while I was following him, until he arrived at his residence. I went to the Masjid and sat there sad and depressed. The Messenger of Allah صلي الله عليه وسلم came out after he performed his purification and said, (Peace and Allah\'s mercy be unto you, peace and Allah\'s mercy be unto you, peace and Allah\'s mercy be unto you.) He then said, (O `Abdullah bin Jabir! Should I inform you of the best Surah in the Qur\'an) I said, `Yes, O Messenger of Allah صلي الله عليه وسلم !\' He said, (Read, `All praise be to Allah, the Lord of the existence,\' until you finish it.)" This Hadith has a good chain of narrators.\nSome scholars relied on this Hadith as evidence that some Ayat and Surahs have more virtues than others.\nFurthermore, in the chapter about the virtues of the Qur\'an, Al-Bukhari recorded that Abu Sa`id Al-Khudri said, "Once, we were on a journey when a female servant came and said, `The leader of this area has been poisoned and our people are away. Is there a healer among you\' Then a man whose healing expertise did not interest us stood for her, he read a Ruqyah for him, and he was healed. The chief gave him thirty sheep as a gift and some milk. When he came back to us we said to him, `You know of a (new) Ruqyah, or did you do this before\' He said, `I only used Umm Al-Kitab as Ruqyah.\' We said, `Do not do anything further until we ask the Messenger of Allah صلي الله عليه وسلم.\' When we went back to Al-Madinah we mentioned what had happened to the Prophet صلي الله عليه وسلم. The Prophet صلي الله عليه وسلم said,\n(وما كان يدريه انها رقيه اقسموا واضربوا لي بسهم)\n(Who told him that it is a Ruqyah Divide (the sheep) and reserve a share for me.)"\nAlso, Muslim recorded in his Sahih, and An-Nasa\'i in his Sunan that Ibn `Abbas said, "While Jibril (Gabriel) was with the Messenger of Allah صلي الله عليه وسلم, he heard a noise from above. Jibril lifted his sight to the sky and said, `This is a door in heaven being open, and it has never been opened before now.\' An angel descended from that door and came to the Prophet صلي الله عليه وسلم and said, `Receive the glad tidings of two lights that you have been given, which no other Prophet before you was given: the Opening of the Book and the last (three) Ayat of Surat Al-Baqarah. You will not read a letter of them, but will gain its benefit."\' This is the wording collected by An-Nasa\'i (Al-Kubra 5:12) and Muslim recorded similar wording (سوره 1 الايه 554).\nAl-Fatihah and the Prayer\nMuslim recorded that Abu Hurayrah said that the Prophet صلي الله عليه وسلم said,\n(من صلي صلاه لم يقرا فيها ام القران فهي خداج ثلاثا غير تمام)\n(Whoever performs any prayer in which he did not read Umm Al-Qur\'an, then his prayer is incomplete.) He said it thrice.\nAbu Hurayrah was asked, "When we stand behind the Imam" He said, "Read it to yourself, for I heard the Messenger of Allah صلي الله عليه وسلم say,\n( قال الله عز وجل: قسمت الصلاه بيني وبين عبدي نصفين ولعبدي ما سال فاذا قال:\nالحمد لله رب العلمين ، قال الله: حمدني عبدي واذا قال:\nالرحمن الرحيم ، قال الله: اثني علي عبدي، فاذا قال:\nملك يوم الدين ، قال الله: مجدني عبدي وقال مره: فوض الي عبدي فاذا قال:\nاياك نعبد واياك نستعين ، قال: هذا بيني وبين عبدي ولعبدي ما سال، فاذا قال:\nاهدنا الصراط المستقيم - صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين ، قال الله: هذا لعبدي ولعبدي ما سال)\n(Allah, the Exalted, said, `I have divided the prayer (Al-Fatihah) into two halves between Myself and My servant, and My servant shall have what he asks for.\' If he says,\nبسم الله الرحمن الرحيم\n(1 In the Name of Allah, the Most Gracious, the Most Merciful.)\nالحمد لله رب العلمين\n(2 All praise and thanks be to Allah, the Lord of existence.)\nAllah says, `My servant has praised Me.\' When the servant says,\nالرحمن الرحيم\n(3 The Most Gracious, the Most Merciful.)\nAllah says, `My servant has glorified Me.\' When he says,\nملك يوم الدين\n(4 The Owner of the Day of Recompense.) Allah says, `My servant has glorified Me,\' or `My servant has related all matters to Me.\' When he says,\nاياك نعبد واياك نستعين\n(5 You (alone) we worship, and You (alone) we ask for help.) Allah says, `This is between Me and My servant, and My servant shall acquire what he sought.\' When he says,\nاهدنا الصراط المستقيم - صراط الذين انعمت عليهم غير المغضوب عليهم ولا الضالين\n(6 Guide us to the straight path.) (7 The way of those on whom You have granted Your grace, not (the way) of those who earned Your anger, nor of those who went astray), Allah says, `This is for My servant, and My servant shall acquire what he asked for.\')."\nThese are the words of An-Nasa\'i, while both Muslim and An-Nasa\'i collected the following wording, "A half of it is for Me and a half for My servant, and My servant shall acquire what he asked for."\nExplaining this Hadith\nThe last Hadith used the word Salah `prayer\' in reference to reciting the Qur\'an, (Al-Fatihah in this case) just as Allah said in another Ayah,\nولا تجهر بصلاتك ولا تخافت بها وابتغ بين ذلك سبيلا\n(And offer your Salah (prayer) neither aloud nor in a low voice, but follow a way between.) meaning, with your recitation of the Qur\'an, as the Sahih related from Ibn `Abbas. Also, in the last Hadith, Allah said, "I have divided the prayer between Myself and My servant into two halves, a half for Me and a half for My servant. My servant shall have what he asked for." Allah next explained the division that involves reciting Al-Fatihah, demonstrating the importance of reciting the Qur\'an during the prayer, which is one of the prayer\'s greatest pillars. Hence, the word `prayer\' was used here although only a part of it was actually being referred to, that is, reciting the Qur\'an. Similarly, the word `recite\' was used where prayer is meant, as demonstrated by Allah\'s statement,\nوقرءان الفجر ان قرءان الفجر كان مشهودا\n(And recite the Qur\'an in the early dawn.Verily, the recitation of the Qur\'an in the early dawn is ever witnessed.) in reference to the Fajr prayer. The Two Sahihs recorded that the angels of the night and the day attend this prayer.\nReciting Al-Fatihah is required in Every Rak`ah of the Prayer\nAll of these facts testify to the requirement that reciting the Qur\'an (Al-Fatihah) in the prayer is required, and there is a consensus between the scholars on this ruling. The Hadith that we mentioned also testifies to this fact, for the Prophet صلي الله عليه وسلم said,\n(من صلي صلاه لم يقرا فيها بام القران فهي خداج)\n(Whoever performs any prayer in which he did not recite Umm Al-Qur\'an, his prayer is incomplete.)\nAlso, the Two Sahihs recorded that `Ubadah bin As-Samit said that the Messenger of Allah صلي الله عليه وسلم said,\n(لا صلاه لمن لم يقرا بفاتحه الكتاب)\n(There is no prayer for whoever does not recite the Opening of the Book.)\nAlso, the Sahihs of Ibn Khuzaymah and Ibn Hibban recorded that Abu Hurayrah said that the Messenger of Allah صلي الله عليه وسلم said,\n(لا تجزي صلاه لا يقرا فيها بام القران)\n(The prayer during which Umm Al-Qur\'an is not recited is invalid.)\nThere are many other Hadiths on this subject. Therefore, reciting the Opening of the Book, during the prayer by the Imam and those praying behind him, is required in every prayer, and in every Rak`ah.\nThe Tafsir of Isti`adhah (seeking Refuge)\nAllah said,\nخذ العفو وامر بالعرف واعرض عن الجهلين - واما ينزغنك من الشيطن نزغ فاستعذ بالله انه سميع عليم\n(Show forgiveness, enjoin what is good, and stay away from the foolish (i.e. don\'t punish them). And if an evil whisper comes to you from Shaytan (Satan), then seek refuge with Allah. Verily, He is Hearing, Knowing) (سوره 7 الايه 199200),\nادفع بالتي هي احسن السييه نحن اعلم بما يصفون - وقل رب اعوذ بك من همزات الشيطين - واعوذ بك رب ان يحضرون\n(Repel evil with that which is better. We are Best-Acquainted with things they utter. And say: "My Lord! I seek refuge with You from the whisperings (suggestions) of the Shayatin (devils). And I seek refuge with You, My Lord! lest they should come near me.") (سوره 23 الايه 9698) and,\nولا تستوي الحسنه ولا السييه ادفع بالتي هي احسن فاذا الذي بينك وبينه عداوه كانه ولي حميم - وما يلقاها الا الذين صبروا وما يلقاها الا ذو حظ عظيم - واما ينزغنك من الشيطن نزغ فاستعذ بالله انه هو السميع العليم\n(Repel (an evil) with one which is better, then verily he with whom there was enmity between you, (will become) as though he was a close friend. But none is granted it except those who are patient and none is granted it except the owner of the great portion (of happiness in the Hereafter, i.e. Paradise and of a high moral character) in this world. And if an evil whisper from Shaytan tries to turn you away (O Muhammad صلي الله عليه وسلم) (from doing good), then seek refuge in Allah. Verily, He is the Hearing, the Knowing.) (سوره 41 الايه 3436) These are the only three Ayat that carry this meaning. Allah commanded that we be lenient human enemy, so that his soft nature might make him an ally and a supporter. He also commanded that we seek refuge from the satanic enemy, because the devil does not relent in his enmity if we treat him with kindness and leniency. The devil only seeks the destruction of the Son of Adam due to the vicious enmity and hatred he has always had towards man\'s father, Adam. Allah said,\nيبني ادم لا يفتننكم الشيطن كما اخرج ابويكم من الجنه\n(O Children of Adam! Let not Shaytan deceive you, as he got your parents Adam and Hawwa\' (Eve) out of Paradise) (سوره 7 الايه 27),\nان الشيطن لكم عدو فاتخذوه عدوا انما يدعو حزبه ليكونوا من اصحب السعير\n(Surely, Shaytan is an enemy to you, so take (treat) him as an enemy. He only invites his Hizb (followers) that they may become the dwellers of the blazing Fire) (سوره 35 الايه 6) and,\nافتتخذونه وذريته اولياء من دوني وهم لكم عدو بيس للظلمين بدلا\n(Will you then take him (Iblis) and his offspring as protectors and helpers rather than Me while they are enemies to you What an evil is the exchange for the Zalimun (polytheists, and wrongdoers, etc)) (سوره 18 الايه 50).\nThe devil assured Adam that he wanted to advise him, but he was lying. Hence, how would he treat us after he had vowed,\nفبعزتك لاغوينهم اجمعين الا عبادك منهم المخلصين\n("By Your might, then I will surely, mislead them all. Except Your chosen servants among them (i.e. faithful, obedient, true believers of Islamic Monotheism).") (سوره 38 الايه 8283)\nAlso, Allah said,\nفاذا قرات القرءان فاستعذ بالله من الشيطن الرجيم\nانه ليس له سلطان علي الذين ءامنوا وعلي ربهم يتوكلون - انما سلطنه علي الذين يتولونه والذين هم به مشركون\n(So when you want to recite the Qur\'an, seek refuge with Allah from Shaytan, the outcast (the cursed one). Verily, he has no power over those who believe and put their trust only in their Lord (Allah). His power is only over those who obey and follow him (Satan), and those who join partners with Him.) (سوره 16 الايه 98100).\nSeeking Refuge before reciting the Qur\'an\nAllah said,\nفاذا قرات القرءان فاستعذ بالله من الشيطن الرجيم\n(So when you want to recite the Qur\'an, seek refuge with Allah from Shaytan, the outcast (the cursed one).) meaning, before you recite the Qur\'an. Similarly, Allah said,\nاذا قمتم الي الصلوه فاغسلوا وجوهكم وايديكم\n(When you intend to offer As-Salah (the prayer), wash your faces and your hands (forearms)) (سوره 5 الايه 6) meaning, before you stand in prayer, as evident by the Hadiths that we mentioned. Imam Ahmad recorded that Abu Sa`id Al-Khudri said, "When the Messenger of Allah صلي الله عليه وسلم would stand up in prayer at night, he would start his prayer

In [10]:
df["tafseer"] = df["Text"].apply(preprocess_tafsir_text)

In [11]:
df

,Surah Number,Ayah Number,Text,tafseer
0,1,1,Introduction to Fatihah\nWhich was revealed in...,Introduction to Fatihah\nWhich was revealed in...
1,1,2,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...
2,1,3,"Allah said next,\nالرَّحْمَـنِ الرَّحِيمِ\n(Ar...","Allah said next,\nالرحمن الرحيم\n(Ar-Rahman (t..."
3,1,4,Indicating Sovereignty on the Day of Judgment\...,Indicating Sovereignty on the Day of Judgment\...
4,1,5,The Linguistic and Religious Meaning of `Ibada...,The Linguistic and Religious Meaning of `Ibada...
...,...,...,...,...
6231,114,2,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...,Which was revealed in Makkah\nبسم الله الرحمن ...
6232,114,3,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...,Which was revealed in Makkah\nبسم الله الرحمن ...
6233,114,4,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...,Which was revealed in Makkah\nبسم الله الرحمن ...
6234,114,5,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...,Which was revealed in Makkah\nبسم الله الرحمن ...
6235,114,6,Which was revealed in Makkah\nبِسْمِ اللَّهِ ا...,Which was revealed in Makkah\nبسم الله الرحمن ...

In [12]:
df.drop('Text', axis=1, inplace=True)

In [13]:
df

,Surah Number,Ayah Number,tafseer
0,1,1,Introduction to Fatihah\nWhich was revealed in...
1,1,2,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...
2,1,3,"Allah said next,\nالرحمن الرحيم\n(Ar-Rahman (t..."
3,1,4,Indicating Sovereignty on the Day of Judgment\...
4,1,5,The Linguistic and Religious Meaning of `Ibada...
...,...,...,...
6231,114,2,Which was revealed in Makkah\nبسم الله الرحمن ...
6232,114,3,Which was revealed in Makkah\nبسم الله الرحمن ...
6233,114,4,Which was revealed in Makkah\nبسم الله الرحمن ...
6234,114,5,Which was revealed in Makkah\nبسم الله الرحمن ...
6235,114,6,Which was revealed in Makkah\nبسم الله الرحمن ...

In [17]:
df = df.sort_values(["Surah Number", "Ayah Number"]).reset_index(drop=True)

df['group'] = (df['tafseer'] != df['tafseer'].shift()) | (df['Surah Number'] != df['Surah Number'].shift())
df['group_id'] = df['group'].cumsum()

result = df.groupby(['Surah Number','group_id']).agg(
    surah_no=('Surah Number', 'first'),
    ayah_start=('Ayah Number', 'min'),
    ayah_end=('Ayah Number', 'max'),
    tafseer=('tafseer', 'first')
).reset_index(drop=True)

result

,surah_no,ayah_start,ayah_end,tafseer
0,1,1,1,Introduction to Fatihah\nWhich was revealed in...
1,1,2,2,The Meaning of Al-Hamd\nAbu Ja`far bin Jarir s...
2,1,3,3,"Allah said next,\nالرحمن الرحيم\n(Ar-Rahman (t..."
3,1,4,4,Indicating Sovereignty on the Day of Judgment\...
4,1,5,5,The Linguistic and Religious Meaning of `Ibada...
...,...,...,...,...
1891,110,1,3,The Virtues of Surat An-Nasr\nIt has been ment...
1892,111,1,5,Which was revealed in Makkah\nبسم الله الرحمن ...
1893,112,1,4,Which was revealed in Makkah\nThe Reason for t...
1894,113,1,5,Which was revealed in Makkah\nThe Position of ...
1895,114,1,6,Which was revealed in Makkah\nبسم الله الرحمن ...

In [20]:
duplicates = result[result.duplicated(subset=['tafseer'], keep=False)]
duplicates

,surah_no,ayah_start,ayah_end,tafseer
1885,104,1,9,Which was revealed in Makkah\nبسم الله الرحمن ...
1886,105,1,5,Which was revealed in Makkah\nبسم الله الرحمن ...

In [25]:
result.loc[result['surah_no'] == 105, 'tafseer'] = f"""
This [event] is one of the blessings Allah granted to the Quraysh: He protected them from the people of the Elephant (the army of Abraha) who had planned to destroy the Kaaba and erase it from existence. Allah destroyed them, humiliated them, ruined their plans, and made their efforts fail, returning them defeated. They were Christians at the time, whose religion was, in some ways, closer to monotheism than the Quraysh’s idolatry.

However, this incident also served as a preparation and prelude for the coming of the Prophet Muhammad (peace be upon him). That year, according to most accounts, he was born. It is as if destiny itself was saying: “We did not grant you victory over the Abyssinians because of your superiority, O Quraysh, but rather to protect the Ancient House [the Kaaba] that we will honor through the mission of the Prophet Muhammad (peace and blessings be upon him), the last of the prophets.”

The Story of the People of the Elephant (Summary)

Previously, in the story of Ashab al-Akhduud (People of the Ditch), we learn that Dhu Nuwas, the last king of Himyar and a polytheist, killed nearly twenty thousand Christians. Only Daws Dhuth Thalban escaped. He sought help from Caesar of Syria, a Christian, who wrote to the Negus (king) of Abyssinia. The Negus sent two commanders, Ariyat and Abraha ibn al-Sabbah Abu Yaksum, with a large army. They entered Yemen, defeated Dhu Nuwas (who drowned in the sea), and Abyssinia took control of Yemen, ruled by these two commanders.

Arifat and Abraha fought over leadership, and eventually Abraha became the sole ruler of the Abyssinian army in Yemen. He wrote to the Negus, who admonished him, and Abraha sent gifts, including Yemeni soil in a bag. He boasted in his letter: “Step on this bag with your kingdom, and here is my head that I send to you.” The Negus was pleased and approved of his actions.

Abraha decided to build a magnificent church in Yemen, intending to divert the Arabs’ pilgrimage from the Kaaba to this church. It was so high and grand that it was called al-Qullays (“the lofty”) by the Arabs. However, the Arabs strongly rejected this, especially the Quraysh, who were angry at this challenge to their sacred site.

The March Toward the Kaaba

Abraha assembled a massive army to attack Mecca. He brought with him a huge elephant named Mahmoud, along with others (some accounts say 8 or 12 elephants). The plan was to use chains to demolish the Kaaba stone by stone. When the Arabs heard of this, they prepared to defend the Kaaba. A Yemeni noble, Dhu Nufar, gathered men to fight and protect the House of Allah.

Abdul Muttalib, the grandfather of the Prophet Muhammad, met Abraha when his army approached Mecca. He requested the return of his camels that had been taken, but he refused to negotiate the Kaaba itself, saying:

“This is the House of Allah, and if anyone prevents access to it, it is Allah Himself who protects it.”

Despite attempts to turn the elephants toward the Kaaba, Mahmoud refused to move. The army tried to force him in several directions, but the elephant would not advance.

Divine Intervention

Allah sent flocks of birds (Tayran Ababil) from the sea. Each bird carried three stones—one in its beak and two in its claws, the size of chickpeas or lentils. They dropped these stones on the Abyssinian army, destroying them. Many soldiers died instantly; some were killed gradually while fleeing. Abraha himself was wounded and died later in Yemen.

This event showed Allah’s protection over the Kaaba and foreshadowed the coming of the Prophet Muhammad (peace be upon him). It is mentioned in the Qur’an:

“Have you not seen how your Lord dealt with the people of the Elephant? Did He not make their plan go astray? And He sent against them birds in flocks, striking them with stones of baked clay, and made them like eaten straw.” (Surah Al-Fil 105:1–5)

The birds are called Ababil, meaning successive flocks or groups. Sijjil refers to hard stones mixed with clay. “Like eaten straw” indicates their complete destruction and humiliation.
"""

print(result[result['surah_no'] == 105])

      surah_no  ayah_start  ayah_end  \
1886       105           1         5

                                                tafseer
1886  \nThis [event] is one of the blessings Allah g...

In [27]:
duplicates = result[result.duplicated(subset=['tafseer'], keep=False)]
duplicates

Empty DataFrame
Columns: [surah_no, ayah_start, ayah_end, tafseer]
Index: []

In [26]:
result.to_csv(
    "tafsir_ibn_kathir_final.csv",
    index=False,
    encoding="utf-8-sig"
)